[package]
name = "visualizer"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]

[dependencies]
alga         = "*"
derive-error = "*"
genmesh      = "*"
glium        = "*"
glutin       = "0.17"
image        = "*"
nalgebra     = "*"
num          = "*"
obj          = "*"
